name: Docker build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # Runs a single command using the runners shell
      - name: Build container
        run: |
          docker build . -t s1ephen/react-client:v1.1
      - name: Docker push
        run: |
          docker push s1ephen/react-client:v1.1
